encoding : "UTF-8"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Technical History

author: 윤순혁

email: shysh@naver.com

description: 기술 메모 및 작업 이력 관리

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

lang: ko
timezone: Asia/Seoul

# Social media
github_username:  SoonhyukYoon

# Plugins
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - Rakefile

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

theme: jekyll-theme-slate